apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "simpleapp.fullname" . }}
  labels:
    app.kubernetes.io/stack: 
      {{ include "simpleapp.fullname" . }}
    {{- include "simpleapp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "simpleapp.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "simpleapp.fullname" . }}
    spec:
      {{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: 3
          topologyKey: topology.kubernetes.io/node
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: {{ include "simpleapp.fullname" . }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sample-demo
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ include "simpleapp.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ports.containerPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

